.. vim: syntax=rst

Sample Elevation Data from Points and LiDAR
===========================================

Elevation Points
----------------

Load Data
~~~~~~~~~

|Sample014| |Sample015|

1. Click on *Layer*>\ *Add Layers* >\ *Add Delimited Text Layer* or click on the *Open Data Source Manager* icon and navigate to the *Delimited Text* tab.
   Add the delimited text data, following the figure below.

2. There are many options to help sort the data.
   Select the options that reflect the desired dataset and click *add.*

.. image:: media\Sample002.png
   :width: 6.61192in
   :height: 5.06782in

Apply a Style
-------------

The data has a default style so it isn’t very easy to view elevation.

1. Adjust the Style properties of the elevation data to assist the quality control measures for reviewing the data.
   For example, elevation data that has a large range can wash out the detail in local areas of the project area.

2. Double click the layer to open the *Properties* window and select the style tab to perform the following.

3. Assign graduated colors;

4. Select field to represent colors;

5. Select color ramp;

6. Classify the data (classifying the data adjustments will assist in locating erroneous data).

.. image:: media\Sample003.png
   :alt: C:\Users\ALEJAN~1\AppData\Local\Temp\SNAGHTML2eb0f1db.PNG
   :width: 5.38576in
   :height: 5.57292in

7. The point data style is a graduated color scheme set to the elevation scale (see figure below).

.. image:: media\Sample004.png
   :width: 6.42177in
   :height: 2.875in

Sample Data
-----------

1. Click the *Assign Elevation to Grid from Points Layer* icon to interpolate the elevation data to the grid.

.. image:: media\Sample005.png
   :width: 4.44585in
   :height: 1.53125in

2. The sampling dialog box appears to select the point source, elevation field, and calculation type.

3. Choose a max search distance to extend the search for empty grid elements.
   The distance is in the native map units.

4. This field can be assigned a zero value to default to the minimum search distance.

.. image:: media\Sample006.png
   :alt: Graphical user interface, application Description automatically
   generated
   :width: 3.62455in
   :height: 4.14531in

.. image:: media\Sample007.png
   :alt: Graphical user interface, text, application Description
   automatically generated
   :width: 3.79119in
   :height: 4.33279in

5. Once the calculation is complete, the following dialog is displayed.
   Click *OK* to continue.

.. image:: media\Sample008.png
   :width: 2.17708in
   :height: 1.2281in

6. The elevation data is saved to the *Grid* Layer in the *Schematic Layers* group.

.. image:: media\Sample009.png
   :alt: C:\Users\ALEJAN~1\AppData\Local\Temp\SNAGHTML683e3dcb.PNG
   :width: 6.3716in
   :height: 3.96875in

LiDAR Data
----------

The LiDAR method can interpolate data from multiple files.
It applies a simple average to the point within a cell and can patch missing LiDAR elevation from areas that are filtered from the ground data
category.

1. Click the *Assign Elevation to Grid from Points Layer* icon to interpolate the elevation data to the grid.

.. image:: media\Sample005.png
   :width: 4.44383in
   :height: 1.45833in

2. Select the bare earth data LiDAR data files that cover the project area.
   These are determined using the LiDAR tiles shapefile.
   Click Open.
   The LiDAR file must have a \*.txt extension.

.. image:: media\Sample010.png
   :width: 6.36379in
   :height: 6.67625in

3. When the file is processing, two progress bars can be seen in QGIS.

.. image:: media\Sample011.png
   :width: 6.48958in
   :height: 5.16667in

4. LiDAR data is bare earth data so categories such as buildings, bridges, overpasses are removed from the point data.

.. image:: media\Sample012.png

5. The plugin will fill this data with a nearest neighbor patch.
   Select the first option and click ok to fill the missing data.

.. image:: media\Sample013.png
   :width: 4.77083in
   :height: 2.89583in

Troubleshooting
~~~~~~~~~~~~~~~

1. If the elevation data is not visible, check the CRS.
   It may be necessary to transform the data into the correct CRS.

2. If the elevation layer does not show up in the *Sample Elevation Dialog* box, make sure it is a point layer and that it is checked on in the *Layers*
   List.

3. If a Python error appears during the sampling, it may indicate that there is no attribute table.
   Save and reload the project into QGIS and try again.

.. |Sample014| image:: media\Sample014.png
   :width: 0.55in
   :height: 0.55in
.. |Sample015| image:: media\Sample015.png
   :width: 0.45069in
   :height: 0.53295in
