name: Build and publish tutorial document

# Controls when the action will run. 
on:
  # Triggers the workflow on push only for the master branch
  push:
    branches: [ main ]

jobs:
  build_tutorial_document:
    name: Building Sphinx tutorial document and uploading as an artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checking-out repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # adjust the Python version as needed

      - name: Install dependencies
        run: |
          /opt/hostedtoolcache/Python/3.9.18/x64/bin/python3.9 -m pip install -r requirements.txt
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.9.18/x64
          PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages
          Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
          Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
          Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib

      - name: Install sphinxcontrib-youtube
        run: |
          /opt/hostedtoolcache/Python/3.9.18/x64/bin/python3.9 -m pip install sphinxcontrib-youtube
        shell: bash
  
      - name: Build Sphinx Documentation
        run: |
          sphinx-build -b html source build
        shell: bash

      - uses: actions/upload-artifact@v1
        name: Zipping and uploading HTML static files as an artifact
        with:
          name: FLO2D_Tutorial
          path: build/

  publish_tutorial_document:
      name: Publishing tutorial document
      needs: [build_tutorial_document]
      runs-on: ubuntu-latest
      steps:
      - uses: actions/download-artifact@v2
        with:
          name: FLO2D_Tutorial
          path: build/

      - name: Commiting tutorial document changes
        run: |
          git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
          cp -r build/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update tutorial" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
  
      - name: Pushing changes on GitHub Pages branch
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
